pipeline {
    agent any
    
    stages {
        stage('Clonar repositorio') {
            steps {
                echo "Descargando aplicación desde GitHub (rama develop)..."

                git branch: 'develop',
                    url: 'https://github.com/JuanJoseMirandaM/practico-ci-cd.git'
            }
        }
    }
}
